### ISSUE TITLE
Project title filter is not filtering the data

### ISSUE THREAD

**Issue by wortleyjk-codefellows** [serinat/301n3-portfolio#10]
-Filtering based on the project's title header is not working.
-Data attribute for the filter was not existing. It will either need to filter by a different means or define the data attribute.

**Comment by meganwalter** [comment]
```
var populateCategoryDropdown = function(element){
  var $categoryOption = $('<option/>',{
      text:element,
      value:element
    });
  $('#category-filter').append($categoryOption);
}
```

What is this function doing? It is new to me and I would love to know how it works!

**Comment by wortleyjk-codefellows** [comment]
populateCategoryDropdown() is a function where the instructions inside it involves dynamically creating a an element and appending the "category-filter" dropdown menu. $("<option/>"),{ //insert attributes here}) is just jQuery shorthand for Document.createElement('option')

**Comment by meganwalter** [comment]
cool!
