### ISSUE TITLE
Nav menu bugs

### ISSUE THREAD

**Issue by meganwalter** [serinat/301n3-portfolio#13]
1. Once a topic is clicked, --Show All-- no longer works, everything goes away
2. Home icon does not link to anything

**Comment by serinat** [comment]
I think at one point I was talking to Dan about this. He said it's a matter of preference whether or not you want everything to show up or not when you hit "Home". I thought it looked cleaner this way. Does this make sense? I can play with it some more though..

**Comment by meganwalter** [comment]
I thought this was for James' blog, please disregard!

**Comment by serinat** [comment]
Okie
